print("Hello from DevOps !")
print("Hello Jenkins, triggered by push!")
print("Hello Jenkins, intervention de NGROK pour publier le lien local sur internet !")
print("Hello Jenkins, 2eme test du build automatique via le webhook !")
print("Hello Jenkins, Est-ce que tu as bien reçu le mail de résultat du build ?")
print("Hello Jenkins, test test ?")
print("Hello Jenkins, nouveau test ?")
print("Hello Jenkins, test apres correction du url du webhook ")